name: Bug Report
description: Report a reproducible bug
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened and what did you expect?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction Steps
      description: Provide exact commands and input files
    validations:
      required: true
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: OS, Python version, dependency versions
  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Paste relevant logs (remove secrets)
